### ISSUE TITLE
Compiler Error in Geometry.ccp

### ISSUE THREAD

**Issue by michaelnu** [eduard-x/cnc-qt#1]
Hallo,

ich habe in der 0.23 und dem aktuellen Stand einen Compiler-Fehler in der Geometry.cpp bei der Funktion trunc.
Ein #include <math.h> schafft Abhilfe.

Ein tolles Projekt. Danke!

Viele Grüße

Michael

**Comment by eduard-x** [comment]
Hallo Michael,
vielen Dank für die Unterstützung! :) Es freut mich. 
Heute nach der Arbeit werde ich den Fehler reparieren. Gibt's dann die Version 0.2.4
Viele Grüße aus Hannover,
Eduard

**Comment by eduard-x** [comment]
Version 0.2.4 ist da, habe folgendes gemacht:
#include <QtCore/qmath.h>
....
trunc() durch qFloor() ersetzt

**Comment by michaelnu** [comment]
Danke!

**Comment by eduard-x** [comment]
Danke für das Ticket. In nächster Version werde ich std Klassen in Qt Klassen portieren und noch einen Fehler bez. libusb reparieren. Vielleicht am Wochenende wird die v.0.2.5 fertig.
