### ISSUE TITLE
Vista compilation

### ISSUE THREAD

**Issue by LETARTARE** [eduard-x/cnc-qt#3]
Hello,
Bravo, it's a big job to do. Congratulations.

I managed to compile a first version under VISTA and qt-5.9 this morning (svn373).
I managed to launch the program, but some functions do not work yet.
I can load a Gode file.
The 'Settings' causes the program to crash.

I find that the system used for translation does not correspond to the QT standard, also I will try to use the Qt system that will be portable.

To be continued ...

**Comment by eduard-x** [comment]
Hello!
This job was not from me alone. Thanks. 
I'm checking now the compiling and creating of installer under Win7. I think, for USB connection the program must be started with admin rights on Win. Under Linux there is the other solution. 
I'll try to reproduce the settings crash, but it's Windows issue. Not possible to create the settings file? 
The other thing with translation files, so it's easier for users without experience on QtLinguist to create the other translations in trivial text editor. The idea was so.
Regards

**Comment by LETARTARE** [comment]
Hello,
the crash is attributable to me, because I made bad modifications: do not seek!
Regards
